### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by whitewalker007** [imranparuk/speaker-recognition-3d-cnn#1]
Hey, Is the code working? and also can you help me with the dataset you used? Thanks

**Comment by imranparuk** [comment]
yeah it works, I used voxceleb

**Comment by imranparuk** [comment]
if you want, I can upload one or two files so its easier to test

**Comment by whitewalker007** [comment]
Yes, please upload few samples. Thanks

**Comment by imranparuk** [comment]
Ok will do, sorry for the delay.
