### ISSUE TITLE
RuntimeError: bool value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by whitewalker007** [imranparuk/speaker-recognition-3d-cnn#2]
RuntimeError: bool value of Tensor with more than one value is ambiguous. I am getting this error in "loss = CrossEntropyLoss(output, labels)" in train.py under pytorch. Please help

**Comment by imranparuk** [comment]
I'll fix that tonight. I released unfinished code to be honest

**Comment by whitewalker007** [comment]
Okay,  No issues. Do update it today.  Thanks in advance.

**Comment by imranparuk** [comment]
Lol dude, I forgot about this, will do it now.
